### PR TITLE
fix minior bugs + remove useless import

### PR DESCRIPTION
**Pull request by driver005**

### CODE REVIEW

**Comment by hasezoey** [comment]
note that the "unused dsl import" had already a PR at #134

**Comment by driver005** [comment]
fell free to revese it
but the other changes are crutal for async fn

**Comment by hasezoey** [comment]
> fell free to revese it

i just wanted to note that the change had already been suggested previously, i have nothing against using it

**Review by hasezoey — CHANGES_REQUESTED** [review]
please update the test files, see [Development/Testing](https://github.com/Wulf/dsync?tab=readme-ov-file#developmenttesting).
(preferably put those changed tests into the commits that changed them)

also it would be great if there could be a test and compile-test for the async paginate (that does not particularly need to be in this PR)

**Comment by driver005** [comment]
oke i will reverse the change to unused dsl import becuase of #134 
it would be great if someone adds the test

**Review by hasezoey — APPROVED** [review]
Looks ok now, personally i would have liked if the commit messages would follow the style of past commits, though wont a problem here because i will squash it.
(i know that we currently dont have a CONTRIBUTING file)

**Pull request merged**
