### PR TITLE
Fix some things that were broken

### PR DESCRIPTION
**Pull request by hasezoey**
This PR is a small collection of fixes from #104, but refactored to current state dsync and separate from the other changes and not being based on #103, in more detail:
- always have `type ConnectionType` be public (was broken for `once-connection-type`)
- change serde derives to use `serde::` instead of requiring it to be imported (was broken for `once-common-structs`)

these things would likely be catched earlier if the tests would actually be compile tested

### CODE REVIEW

**Review by Wulf — APPROVED** [review]
Looks good to me! Let's merge this in instead of #104

**Comment by Wulf** [comment]
I'm going to add a few more commits here which should take care of some of the chnages which weren't included from #104

**Comment by Wulf** [comment]
ah, I can't seem to do this. Do you mind adding the following changes?

1. Remove 'tsync' from `Cargo.toml`
image


2. In `src/lib.rs`, add the following comment above `pub connection_type: String,`:

```rust
    /// For example:
    /// - `diesel::pg::PgConnection` (default)
    /// - `diesel::sqlite::SqliteConnection`
    /// - `diesel::mysql::MysqlConnection`
    /// - or, your custom diesel connection type (struct which implements `diesel::connection::Connection`)
```
image

3. In `src/lib.rs`, add a default for GenerationConfig before `impl GenerationConfig<'_> {`

```rust
impl<'a> Default for GenerationConfig<'a> {
    fn default() -> Self {
        Self {
            table_options: Default::default(),
            default_table_options: Default::default(),
            connection_type: "diesel::pg::PgConnection".into(),
            diesel_backend: "diesel::pg::Pg".into(),
            schema_path: "crate::schema::".into(),
            model_path: "crate::models::".into(),
            once_common_structs: true,
            once_connection_type: true,
        }
    }
}
```

image


Aaandddd, that should be all! 🙌 

If you're not able to do this, no worries, I can add it in after we merge this in. Just let me know!

**Comment by hasezoey** [comment]
rebased on latest main, and added the `2.` for examples, removing the `(default)` and adding r2d2, also adding that comment to the binary help

as for `1. remove tsync feature default`  and `3. GenerationConfig default derive`, this should likely be done in a separate PR
(the tsync attribute is not added by default and would require a argument (`--tsync`) in addition to having the feature enabled; generation config default derive would likely need some refactoring to make it work with good defaults (like `connection_type`)

**Pull request merged**
