### PR TITLE
fix(code): rename "type Connection" to "type ConnectionType"

### PR DESCRIPTION
**Pull request by hasezoey**
to lessen conflicts with diesel's "Connection" trait

re #56

i am open to other names aside from `ConnectionType`

### CODE REVIEW

**Review by Wulf — APPROVED** [review]

**Comment by Wulf** [comment]
Awesome, so we won't need a CLI arg for this then, right?

**Comment by hasezoey** [comment]
> Awesome, so we won't need a CLI arg for this then, right?

i could make one, should i?

**Comment by hasezoey** [comment]
updated to resolve conflicts

**Review by Wulf — APPROVED** [review]
:raised_hands:

**Pull request merged**
