### PR TITLE
Add option to generate `Create*` structs without primary key

### PR DESCRIPTION
**Pull request by tpotancok**
In most applications you want an autoincrement field as your primary key (`serial primary key` in Postgres). Diesel does this automatically if the struct passed to `insert_into(db).values()` doesn't have a field for the PK. This adds a table option and CLI flag that skips the PK field when generating `Create*` structs.

### CODE REVIEW

**Comment by Wulf** [comment]
@pooroligarch thanks for this one too :)

I think it's better to specify the columns as auto-generated because it will also produce the right update struct. Perhaps the `-g id` flag is enough for your use case. You can specify auto-generated columns per-table or globally. 

Please let me know what you think!~

**Comment by Wulf** [comment]
I'm hesitant to add this because it adds complexity to the already existing list of scenarios possible when generating structs.

Instead, could I request that, if your flag is present, you add all primary key columns to the config's autogenerated columns array before any processing occurs; so perhaps [above this line](https://github.com/Wulf/dsync/blob/main/src/lib.rs#L113)? Perhaps a rename of the flag is also necessary -- something like `--autogenerated-primary-keys`?

**Comment by hasezoey** [comment]
seeing as changes have been requested (by https://github.com/Wulf/dsync/pull/27#issuecomment-1480340815) and the base branch has advanced to have conflicts with this PR and no response since the comment, i would close this PR if it does not get any activity within the next month

**Comment by Wulf** [comment]
@tpotancok I'm going to close this but feel free to reopen

**Pull request closed without merging**
