### PR TITLE
feat: add options "create-str" and "update-str"

### PR DESCRIPTION
**Pull request by hasezoey**
This PR adds options `create-str` and `update-str` to set which string type to use, this can be useful over just `String`, because those structs may not need to own their values, but the normal (`StructType::Read`) will still need to own it values

re #56

### CODE REVIEW

**Comment by Wulf** [comment]
Looks good to me @hasezoey, could I request that we simplify the tests by only including a string field for the Todo model and nothing else? If you think it provides value, I'm okay with it 🙌 !

**Review by Wulf — APPROVED** [review]

**Comment by hasezoey** [comment]
> could I request that we simplify the tests by only including a string field for the Todo model and nothing else?

sure, i basically just always copy `simple_table` as a go-to test

**Comment by hasezoey** [comment]
Update:
- changed test schema to only include necessary fields
- added some extra fields (nullable) for testing
- noticed that nullable was not correctly handled, and fixed it (as a side-effect Update structs are now `Option<TYPE>` instead of `Option<Option<TYPE>>`)

**Comment by Wulf** [comment]
> noticed that nullable was not correctly handled, and fixed it (as a side-effect Update structs are now Option<TYPE> instead of Option<Option<TYPE>>)

Can you give an example here? We don't want to remove `Option<Option<TYPE>>` because that makes the API less flexible.

Currently, you can update the fields you're interested in and set `None` for the rest.

Here's an example:

Imagine we had this table:
```rust
diesel::table! {
    todos (id) {
        text -> Text,
        text_nullable -> Nullable<Text>,
    }
}
```

Here's what `dsync` will generate:
```rust
pub struct UpdateTodo {
    pub text: Option<String>,
    pub text_nullable: Option<Option<String>>,
}
```

And here are some example queries:

1. This would not update any of the fields:
    ```rust
        Todo::update(.., .., &UpdateTodo {
            text: None,
            text_nullable: None,
        });
    ```

2. This will only update the 'text' field:
    ```rust
        Todo::update(.., .., &UpdateTodo {
            text: Some("updated!".to_string()),
            text_nullable: None,
        });
    ```

3. This will set text_nullable to NULL
    ```rust
        Todo::update(.., .., &UpdateTodo {
            text: None,
            text_nullable: Some(None),
        });
    ```

4. This will set text_nullable:
    ```rust
        Todo::update(.., .., &UpdateTodo {
            text: None,
            text_nullable: Some(Some("updated!".to_string())),
        });
    ```

**Comment by hasezoey** [comment]
> Can you give an example here? We don't want to remove Option<Option<TYPE>> because that makes the API less flexible.

thanks for pointing this out, i will fix it.

the problem i fixed with that was that `base_type`(which to my knowledge is meant to actually be the **base** type) was set to `Option<BASE_TYPE>` within `fields()`, and then set again in `render()`, resulting that checks on `base_type` would fail (ie `base_type == "String"`) because it was already `Option<String>`, but there was also the extra property of `is_optional` which was set and so resulted in `Option<Option<BASE_TYPE>>`.

please clarify on what function `fields()` and `render()`'s purposes are, because currently they handle somewhat of many things, like `fields()` will set `is_optional` if the struct type is `Update`, but so losing the original `is_optional`, previously it also wrapped `base_type` in `Option` and `render` wrapped it again

example of fixing the current state:

(context [this line](https://github.com/Wulf/dsync/blob/9fa54f71cbbcbe8326934fa0ff164c8e3f9b2564/src/code.rs#L289))
```diff
-let field_type = if f.is_optional {
+let mut field_type = if f.is_optional {
    format!("Option<{}>", base_type)
} else {
    base_type.into()
};

+if self.ty == StructType::Update {
+    field_type = format!("Option<{}>", field_type);
+}
```

but then we would also need to remove the following lines:
https://github.com/Wulf/dsync/blob/9fa54f71cbbcbe8326934fa0ff164c8e3f9b2564/src/code.rs#L199-L206

because otherwise (as mentioned earlier) `fields()` will always set `is_optional` if struct-type is `Update`, and so changing all properties (regardless of `nullable`) to be `Option<Option<BASE_TYPE>>`

or do know a better solution?

i will make a separate PR (and let this PR depend on it) to try to refactor how those functions work

**Comment by hasezoey** [comment]
> i will make a separate PR (and let this PR depend on it) to try to refactor how those functions work

the PR is now created as #85 

Blocked until #85 is merged / a other solution is found

**Comment by hasezoey** [comment]
PR #85 is merged, and this PR has been rebased to use the merged code, dropping the problematic commit (also adjusting for changes from that PR)

@Wulf is this PR good now?

**Review by Wulf — APPROVED** [review]
@hasezoey looks good to me :-)
🙌

**Pull request merged**
