### PR TITLE
Add option `single-model-file`

### PR DESCRIPTION
**Pull request by hasezoey**
This PR adds the option `single-model-file` to only generate a single file instead of a directory with a `mod.rs` and `generated.rs`

re #56 

This PR uses a commit from #80

### CODE REVIEW

**Review by Wulf — CHANGES_REQUESTED** [review]
Nice, again, similar to the other CR, I've got a request regarding tests:

Can you use a schema file which has multiple tables? This will help us document and test the behaviour. Moreover, we can get rid of all the other fields since that behaviour is already tested for!

```
diesel::table! {
    todos (id) {
        id -> Int4,
    }
}

diesel::table! {
    users (id) {
        id -> Int4,
    }
}
```

**Comment by hasezoey** [comment]
changed to add second table, and only the primary key fields remain

**Review by Wulf — APPROVED** [review]
Nice, thanks for updating the tests

**Comment by hasezoey** [comment]
rebased on latest master, also include #86 to fix clippy (because it is a simple fix and the other PR would require a review first)

**Pull request merged**
