### PR TITLE
Ci run test scripts

### PR DESCRIPTION
**Pull request by AnthonyMichaelTDM**
also fixes the error causing the CI to fail

sorry I didn't notice it in my previous review of #3

### CODE REVIEW

**Comment by AnthonyMichaelTDM** [comment]
also, note that the current contents of ./test/simple_schema are out of date and as such the test will fail

should I run the test script and commit the results @Wulf ?

**Comment by AnthonyMichaelTDM** [comment]
sorry about the commit spam, I have to fix these issues one at a time because the version of clippy run by the gh action seems to catch more things than I do when i run it on my computer

**Comment by AnthonyMichaelTDM** [comment]
@Wulf this adds a job to run the test_all script, it also fixes what's causing all the test runs to fail rn

**Comment by AnthonyMichaelTDM** [comment]
@Wulf can I get a review?

**Comment by AnthonyMichaelTDM** [comment]
trying to figure out what's causing this rn ...
image

**Comment by AnthonyMichaelTDM** [comment]
That was embarrassing, should be fixed now though, lol.

**Comment by Wulf** [comment]
:rocket: awesome! Looks good to me!

**Pull request merged**
